--ALTER TABLE BWADMIN.BANK_ACCOUNT
--ADD CONSTRAINT FK_BANK_ACCOUNT_CLIENT_ID
--FOREIGN KEY (USER_ID) REFERENCES BWADMIN.BANK_CLIENT(CLIENT_ID);
--
--ALTER TABLE BWADMIN.BANK_ACCOUNT
--DROP CONSTRAINT FK_USER_ID;
/


--DROP TRIGGER IWP1ADMIN.TR_INSERT_INVOICES;
--/

--DROP SEQUENCE IWP1ADMIN.SQ_EMPLOYEE_PK;
--/

DROP TABLE IWP1ADMIN.TITLES;
/


INSERT INTO IWP1ADMIN.AUTH (USER_NAME,PASSWORD)
VALUES('blahblah','slamjam');                               --> SUCCESSFUL TEST
/

DELETE FROM IWP1ADMIN.AUTH 
WHERE USER_NAME = 'amazinjames';                            --> REMOVED TEST
/

UPDATE IWP1ADMIN.EMPLOYEES SET REPORTSTO = 13 WHERE USER_ID = 12;                               --> SUCCESSFUL TEST
/

UPDATE IWP1ADMIN.EMPLOYEES SET FIRST_NAME = 'Imhotep', LAST_NAME = 'Wallace' WHERE USER_ID = 13;                               --> SUCCESSFUL TEST
/

UPDATE IWP1ADMIN.INVOICES SET STATUS = 0, PROCESSEDBY = null, PROCESSDATE = null WHERE INVOICE_ID = 32;
/

INSERT INTO IWP1ADMIN.EMPLOYEES (USER_ID, EMAIL, FIRST_NAME,LAST_NAME, TITLE_ID)
VALUES(12,'alwallace@yahoo.com','Young','Izzy',1000);                               --> SUCCESSFUL TEST
/

INSERT INTO IWP1ADMIN.EMPLOYEES (USER_ID, EMAIL, FIRST_NAME,LAST_NAME, TITLE_ID)
VALUES(13,'imalwallace@gmail.com','Young','Izzy',500);                               --> SUCCESSFUL TEST
/

INSERT INTO IWP1ADMIN.INVOICES (USER_ID, AMOUNT, SUBMITDATE)
VALUES(12, 100.00, CURRENT_DATE);                               --> SUCCESSFUL TEST
/
DELETE FROM IWP1ADMIN.EMPLOYEES 
WHERE FIRST_NAME = 'IMHOTEP';                                             --> REMOVED TEST
/

SELECT USER_NAME FROM BWADMIN.BANK_CLIENT WHERE EXISTS(SELECT USER_NAME  FROM BWADMIN.BANK_CLIENT WHERE USER_NAME= 'BUTTSMITHY');
/
conn iwp1admin/yourmom69;
SELECT USER_NAME FROM IWP1ADMIN.AUTH WHERE USER_NAME = 'blahblah';
/

SELECT TITLE_NAME FROM IWP1ADMIN.TITLES WHERE TITLE_ID = 500;
/

--ALTER TABLE IWP1ADMIN.INVOICES DROP COLUMN SUBMITTED;
--ALTER TABLE IWP1ADMIN.INVOICES DROP COLUMN PROCESSED;
--ALTER TABLE IWP1ADMIN.INVOICES ADD PROCESSEDBY NUMBER;
ALTER TABLE IWP1ADMIN.INVOICES ADD SUBMITDATE DATE;
ALTER TABLE IWP1ADMIN.INVOICES ADD PROCESSDATE DATE;
/
ALTER TABLE IWP1ADMIN.INVOICES MODIFY PROCESSEDBY INTEGER;
/
ALTER TABLE IWP1ADMIN.INVOICES MODIFY STATUS NUMBER(1,0);
/
ALTER TABLE IWP1ADMIN.INVOICES MODIFY AMOUNT NUMBER(38,2);
/


SELECT FIRSTNAME, LASTNAME, IWP1ADMIN.EMPLOYEES.USER_ID, INVOICES.INVOICEID
FROM CHINOOK.CUSTOMER
INNER JOIN CHINOOK.INVOICE ON CUSTOMER.CUSTOMERID=INVOICE.CUSTOMERID;
/
conn iwp1admin/yourmom69;
SELECT EMPLOYEES.USER_ID, INVOICES.INVOICE_ID,
INVOICES.STATUS, INVOICES.AMOUNT, INVOICES.IMAGE_ID, 
INVOICES.PROCESSEDBY, INVOICES.SUBMITDATE, INVOICES.PROCESSDATE
FROM IWP1ADMIN.INVOICES
RIGHT OUTER JOIN IWP1ADMIN.EMPLOYEES ON INVOICES.USER_ID = EMPLOYEES.USER_ID 
WHERE (EMPLOYEES.REPORTSTO = 13) AND (INVOICES.STATUS = 0);
/